import { genSaltSync, hashSync } from "bcryptjs";
import { prisma } from "../postgres";
import { CustomError } from "../../domain/errors/custom.error";

//Función anónima autoinvocada
(async() => {
    
    try {
        
        await mainSeed();

    } catch( error ){

        throw CustomError.internalServerError(`${error}`);

    } finally {

        await prisma.$disconnect();

    }

})();

async function mainSeed() {

    //? ***************************************************** ?//
    //? ********* LIMPIAMOS TABLAS DE BASE DE DATOS ********* ?//
    //? ***************************************************** ?//
    await prisma.sEGU_PQRS.deleteMany();
    await prisma.pQRS_PQRS.deleteMany();
    await prisma.uSER_USERS.deleteMany();

    //* **************************************** *//
    //* ********* REGISTRANDO USUARIOS ********* *//
    //* **************************************** *//
    const salt = genSaltSync();

    await prisma.uSER_USERS.createMany({
        data: [
            {
                id: 1,
                typeDocument: "CC",
                document: "1000000001",
                fullName: "Luis Antonio Carriel",
                email: "luis@correo.com",
                emailValidated: true,
                password: hashSync("_LuisAntonio123", salt),
                roles: ["USER"],
                img: null,
                address: "Carrera 250 # 23 - 432 - Dummie",
                phone: "6043219011",
                cellPhone: "3129100011",
                description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                createDateAt: new Date(),
            },
            {
                id: 2,
                typeDocument: "CC",
                document: "1000000002",
                fullName: "Jerónimo Palomino Barrera",
                email: "jeronimo@correo.com",
                emailValidated: true,
                password: hashSync("_Jeronimo123", salt),
                roles: ["USER"],
                img: null,
                address: "Carrera 123 # 121 - 1 - Dummie",
                phone: "6044390011",
                cellPhone: "3127810001",
                description: "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
                createDateAt: new Date(),
            },
            {
                id: 3,
                typeDocument: "CC",
                document: "1000000003",
                fullName: "Berenice Torres Bedoya",
                email: "berenice@correo.com",
                emailValidated: true,
                password: hashSync("_Berenice123", salt),
                roles: ["USER","DEV"],
                img: null,
                address: "Carrera 11 # 166 - 788 - Dummie",
                phone: "6044329011",
                cellPhone: "3109012177",
                description: "Lorem Ipsum is therefore always free from repetition, injected humour.",
                createDateAt: new Date(),
            },
            {
                id: 4,
                typeDocument: "CC",
                document: "1000000004",
                fullName: "Tatiana Lozano Cano",
                email: "tatiana@correo.com",
                emailValidated: false,
                password: hashSync("_Tatiana123", salt),
                roles: ["USER"],
                img: null,
                address: "Calle 98 # 190 - 667 - Dummie",
                phone: "6044129011",
                cellPhone: "3119028711",
                description: "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.",
                createDateAt: new Date(),
            },
            {
                id: 5,
                typeDocument: "CC",
                document: "1000000005",
                fullName: "Karolain Bedoya Villada",
                email: "karolain@correo.com",
                emailValidated: false,
                password: hashSync("_Karolain123", salt),
                roles: ["USER","DEV"],
                img: null,
                address: "Carrera 121 # 231 - 776 - Dummie",
                phone: "6044893122",
                cellPhone: "3120329981",
                description: "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
                createDateAt: new Date(),
            },
            {
                id: 6,
                typeDocument: "CC",
                document: "1000000006",
                fullName: "Juan Sebastian Medina Toro",
                email: "JSebastian19952011@gmail.com", //Real
                emailValidated: true,
                password: hashSync("_Sebastian123", salt),
                roles: ["USER","DEV","ADMIN"],
                img: null,
                address: "Calle 141 # 11 - 887 - Dummie",
                phone: "6044123181",
                cellPhone: "3156127777",
                description: "The generated Lorem Ipsum is therefore always free from repetition.",
                createDateAt: new Date(),
            },
            {
                id: 7,
                typeDocument: "CC",
                document: "1000000007",
                fullName: "Fabio Medina Henao",
                email: "fabio@correo.com",
                emailValidated: true,
                password: hashSync("_Fabio123", salt),
                roles: ["USER","DEV","ADMIN"],
                img: null,
                address: "Carrera 54A # 101 - 981 - Dummie",
                phone: "6044327810",
                cellPhone: "3120910012",
                description: "Lorem Ipsum passages, and more recently with desktop publishing.",
                createDateAt: new Date(),
            },
            {
                id: 8,
                typeDocument: "CC",
                document: "1000000008",
                fullName: "Hector Danilo Carrasca Gaviria",
                email: "hector@correo.com",
                emailValidated: true,
                password: hashSync("_Hector123", salt),
                roles: ["USER"],
                img: null,
                address: "Calle 119C # 10 - 771 - Dummie",
                phone: "6042459012",
                cellPhone: "3118920122",
                description: "Aldus PageMaker including versions of Lorem Ipsum.",
                createDateAt: new Date(),
            },
            {
                id: 9,
                typeDocument: "CC",
                document: "1000000009",
                fullName: "Victor Hugo Díaz Arredondo",
                email: "victor@correo.com",
                emailValidated: true,
                password: hashSync("_Victor123", salt),
                roles: ["USER"],
                img: null,
                address: "Carrera 100A # 10 - 311 - Dummie",
                phone: "6044509012",
                cellPhone: "3120919901",
                description: "It uses a dictionary of over 200 Latin words, combined with a handful.",
                createDateAt: new Date(),
            },
            {
                id: 10,
                typeDocument: "CC",
                document: "1000000010",
                fullName: "Gabriela Carmona Avila",
                email: "gabriela@correo.com",
                emailValidated: true,
                password: hashSync("_Gabriela123", salt),
                roles: ["USER"],
                img: null,
                address: "Calle 89A # 312C - 566 - Dummie",
                phone: "6043420912",
                cellPhone: "3116718011",
                description: "It uses a dictionary of over 200 Latin words, combined with a handful.",
                createDateAt: new Date(),
            },
            {
                id: 11,
                typeDocument: "CC",
                document: "1000000011",
                fullName: "Carlos Andres Herrera Cano",
                email: "carlos@correo.com",
                emailValidated: false,
                password: hashSync("_Carlos123", salt),
                roles: ["USER"],
                img: null,
                address: "Carrera 55A # 115C - 111 - Dummie",
                phone: "6043129012",
                cellPhone: "3193392201",
                description: "Donec semper vehicula tortor non vulputate.",
                createDateAt: new Date(),
            },
            {
                id: 12,
                typeDocument: "CC",
                document: "1000000012",
                fullName: "Lina Maria Gallego Tobar",
                email: "lina@correo.com",
                emailValidated: true,
                password: hashSync("_Lina123", salt),
                roles: ["USER"],
                img: null,
                address: "Calle 11B # 1C - 111 - Dummie",
                phone: "6042178102",
                cellPhone: "3129012281",
                description: "Nam viverra eros lacus, eget luctus risus facilisis id.",
                createDateAt: new Date(),
            },
            {
                id: 13,
                typeDocument: "CC",
                document: "1000000013",
                fullName: "Cecilia Toro Hinestroza",
                email: "cecilia@correo.com",
                emailValidated: true,
                password: hashSync("_Cecilia123", salt),
                roles: ["USER"],
                img: null,
                address: "Carrera 34A # 2 - 473 - Dummie",
                phone: "6044382011",
                cellPhone: "3167810922",
                description: "Nam feugiat leo nec nisl dapibus, at viverra leo iaculis.",
                createDateAt: new Date(),
            },
            {
                id: 14,
                typeDocument: "CC",
                document: "1000000014",
                fullName: "Bairon Alexis Durán Yepes",
                email: "bairon@correo.com",
                emailValidated: true,
                password: hashSync("_Bairon123", salt),
                roles: ["USER"],
                img: null,
                address: "Calle 45X # 5 - 2234 - Dummie",
                phone: "6043129814",
                cellPhone: "3128710009",
                description: "Curabitur suscipit diam orci, in vulputate dui placerat vel.",
                createDateAt: new Date(),
            }
        ]
    });

    //* ************************************ *//
    //* ********* REGISTRANDO PQRS ********* *//
    //* ************************************ *//
    await prisma.pQRS_PQRS.createMany({
        data: [
            {
                id: 1,
                radicated: "RE271820397291021832",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 1,
            },
            {
                id: 2,
                radicated: "RE574309393494822283",
                requestTypeId: "Queja",
                description: "Esto es una queja. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 1,
            },
            {
                id: 3,
                radicated: "RE003292378374747323",
                requestTypeId: "Sugerencia",
                description: "Esto es una sujerencia. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 2,
            },
            {
                id: 4,
                radicated: "RE819023810774703382",
                requestTypeId: "Queja",
                description: "Esto es una queja. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 3,
            },
            {
                id: 5,
                radicated: "RE908433489072738743",
                requestTypeId: "Queja",
                description: "Esto es una queja. Many desktop publishing packages and web page editors now use.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 3,
            },
            {
                id: 6,
                radicated: "RE274904870327474312",
                requestTypeId: "Queja",
                description: "Esto es una queja. If you are going to use a passage of Lorem Ipsum, you need.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 4,
            },
            {
                id: 7,
                radicated: "RE743290237720904774",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. Lorem Ipsum comes from sections.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 5,
            },
            {
                id: 8,
                radicated: "RE478922348928737421",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. The standard chunk of Lorem Ipsum used since the 1500s is reproduced.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 5,
            },
            {
                id: 9,
                radicated: "RE982013097476611222",
                requestTypeId: "Queja",
                description: "Esto es una queja. Many desktop publishing packages and web page editors now use.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 5,
            },
            {
                id: 10,
                radicated: "RE387928239981228112",
                requestTypeId: "Reconocimiento",
                description: "Esto es una reconocimiento. All the Lorem Ipsum generators on the Internet tend to repeat.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 8,
            },
            {
                id: 11,
                radicated: "RE784328729819011112",
                requestTypeId: "Sugerencia",
                description: "Esto es una sugerencia. Various versions have evolved over the years.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 9,
            },
            {
                id: 12,
                radicated: "RE327422877612737333",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. There are many variations of passages of Lorem Ipsum available.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 10,
            },
            {
                id: 13,
                radicated: "RE901909021298737443",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. If you are going to use a passage of Lorem Ipsum.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 10,
            },
            {
                id: 14,
                radicated: "RE671839432099999102",
                requestTypeId: "Queja",
                description: "Esto es una queja. Lorem Ipsum is therefore always free from repetition.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 10,
            },
            {
                id: 15,
                radicated: "RE092387428723473823",
                requestTypeId: "Reconocimiento",
                description: "Esto es una reconocimiento. Morbi ac accumsan enim, at dictum arcu.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 12,
            },
            {
                id: 16,
                radicated: "RE671694930182732334",
                requestTypeId: "Queja",
                description: "Esto es una queja. Quisque ornare ullamcorper magna sed lobortis.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 13,
            },
            {
                id: 17,
                radicated: "RE741028938108828282",
                requestTypeId: "Queja",
                description: "Esto es una queja. Quisque semper tellus ut ligula efficitur.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 13,
            },
            {
                id: 18,
                radicated: "RE000128927341442323",
                requestTypeId: "Queja",
                description: "Esto es una queja. Proin et dolor et eros pellentesque viverra ac id lacus.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 13,
            },
            {
                id: 19,
                radicated: "RE478239719291999934",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. Morbi convallis, elit ultricies facilisis tristique, ex velit tempor erat.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 14,
            },
            {
                id: 20,
                radicated: "RE163948538292823334",
                requestTypeId: "Solicitud",
                description: "Esto es una solicitud. Vivamus egestas ut ligula eu sodales. Sed blandit euismod eros. Ut blandit, arcu et convallis pharetra.",
                status: "Activa",
                scalingOther: false,
                scalingRadicated: null,
                createDateAt: new Date(),
                userId: 14,
            }
        ]

    });

    //* *************************************************** *//
    //* ********* REGISTRANDO SEGUIMIENTO DE PQRS ********* *//
    //* *************************************************** *//
    await prisma.sEGU_PQRS.createMany({
        data: [
            {
                id: 1,
                status: "Activa",
                response: "Integer mi ligula, malesuada eget venenatis eu, porta ut libero.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 1,
            },
            {
                id: 2,
                status: "Activa",
                response: "Aliquam maximus risus egestas ante dapibus vehicula.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 2,
            },
            {
                id: 3,
                status: "Activa",
                response: "Quisque pulvinar id magna finibus pretium.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 3,
            },
            {
                id: 4,
                status: "Activa",
                response: "Ut enim dolor, vehicula ut metus ac, dignissim convallis mi.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 4,
            },
            {
                id: 5,
                status: "Activa",
                response: "Duis tristique pharetra turpis quis ultricies.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 5,
            },
            {
                id: 6,
                status: "Activa",
                response: "Vestibulum felis ante, condimentum et dapibus sit amet, tempus sit amet velit.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 6,
            },
            {
                id: 7,
                status: "Activa",
                response: "Vestibulum venenatis urna lorem, in euismod ante malesuada bibendum.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 7,
            },
            {
                id: 8,
                status: "Activa",
                response: "In vestibulum interdum hendrerit.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 8,
            },
            {
                id: 9,
                status: "Activa",
                response: "Nunc eget dui posuere quam convallis sollicitudin.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 9,
            },
            {
                id: 10,
                status: "Activa",
                response: "Vestibulum volutpat odio ut dui eleifend, in tincidunt quam lobortis.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 10,
            },
            {
                id: 11,
                status: "Activa",
                response: "Sed dolor elit, sollicitudin in risus vel.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 11,
            },
            {
                id: 12,
                status: "Activa",
                response: "Donec et venenatis sem, id faucibus magna. Nulla vulputate.",
                createDateAt: new Date(),
                employeeId: 6,
                pqrsId: 12,
            },
            {
                id: 13,
                status: "Activa",
                response: "Class aptent taciti sociosqu ad litora torquent per conubia nostra.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 13,
            },
            {
                id: 14,
                status: "Activa",
                response: "Suspendisse suscipit elementum efficitur. Praesent sodales lorem non condimentum vestibulum.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 14,
            },
            {
                id: 15,
                status: "Activa",
                response: "Fusce rhoncus sem sed accumsan imperdiet. Pellentesque dignissim ut orci eget pretium. Sed blandit in mi at iaculis. Cras enim felis, posuere at nisl ut.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 15,
            },
            {
                id: 16,
                status: "Activa",
                response: "Sed vehicula tempus turpis quis ultricies.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 16,
            },
            {
                id: 17,
                status: "Activa",
                response: "Nunc posuere lectus et posuere eleifend. Curabitur eget magna vel magna cursus.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 17,
            },
            {
                id: 18,
                status: "Activa",
                response: "Proin accumsan, neque condimentum varius vestibulum, est sem feugiat nulla.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 18,
            },
            {
                id: 19,
                status: "Activa",
                response: "Curabitur ut enim dictum, tristique ante nec.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 19,
            },
            {
                id: 20,
                status: "Activa",
                response: "Nullam eleifend bibendum dignissim.",
                createDateAt: new Date(),
                employeeId: 7,
                pqrsId: 20,
            },
        ]
    });

    console.log(" ---> SEED EJECUTADOS <--- ");

} 
